require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TJsonEntitiesController do

  # This should return the minimal set of attributes required to create a valid
  # TJsonEntity. As you add validations to TJsonEntity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TJsonEntitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all t_json_entities as @t_json_entities" do
      t_json_entity = TJsonEntity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:t_json_entities).should eq([t_json_entity])
    end
  end

  describe "GET show" do
    it "assigns the requested t_json_entity as @t_json_entity" do
      t_json_entity = TJsonEntity.create! valid_attributes
      get :show, {:id => t_json_entity.to_param}, valid_session
      assigns(:t_json_entity).should eq(t_json_entity)
    end
  end

  describe "GET new" do
    it "assigns a new t_json_entity as @t_json_entity" do
      get :new, {}, valid_session
      assigns(:t_json_entity).should be_a_new(TJsonEntity)
    end
  end

  describe "GET edit" do
    it "assigns the requested t_json_entity as @t_json_entity" do
      t_json_entity = TJsonEntity.create! valid_attributes
      get :edit, {:id => t_json_entity.to_param}, valid_session
      assigns(:t_json_entity).should eq(t_json_entity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TJsonEntity" do
        expect {
          post :create, {:t_json_entity => valid_attributes}, valid_session
        }.to change(TJsonEntity, :count).by(1)
      end

      it "assigns a newly created t_json_entity as @t_json_entity" do
        post :create, {:t_json_entity => valid_attributes}, valid_session
        assigns(:t_json_entity).should be_a(TJsonEntity)
        assigns(:t_json_entity).should be_persisted
      end

      it "redirects to the created t_json_entity" do
        post :create, {:t_json_entity => valid_attributes}, valid_session
        response.should redirect_to(TJsonEntity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved t_json_entity as @t_json_entity" do
        # Trigger the behavior that occurs when invalid params are submitted
        TJsonEntity.any_instance.stub(:save).and_return(false)
        post :create, {:t_json_entity => { "name" => "invalid value" }}, valid_session
        assigns(:t_json_entity).should be_a_new(TJsonEntity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TJsonEntity.any_instance.stub(:save).and_return(false)
        post :create, {:t_json_entity => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested t_json_entity" do
        t_json_entity = TJsonEntity.create! valid_attributes
        # Assuming there are no other t_json_entities in the database, this
        # specifies that the TJsonEntity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TJsonEntity.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => t_json_entity.to_param, :t_json_entity => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested t_json_entity as @t_json_entity" do
        t_json_entity = TJsonEntity.create! valid_attributes
        put :update, {:id => t_json_entity.to_param, :t_json_entity => valid_attributes}, valid_session
        assigns(:t_json_entity).should eq(t_json_entity)
      end

      it "redirects to the t_json_entity" do
        t_json_entity = TJsonEntity.create! valid_attributes
        put :update, {:id => t_json_entity.to_param, :t_json_entity => valid_attributes}, valid_session
        response.should redirect_to(t_json_entity)
      end
    end

    describe "with invalid params" do
      it "assigns the t_json_entity as @t_json_entity" do
        t_json_entity = TJsonEntity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TJsonEntity.any_instance.stub(:save).and_return(false)
        put :update, {:id => t_json_entity.to_param, :t_json_entity => { "name" => "invalid value" }}, valid_session
        assigns(:t_json_entity).should eq(t_json_entity)
      end

      it "re-renders the 'edit' template" do
        t_json_entity = TJsonEntity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TJsonEntity.any_instance.stub(:save).and_return(false)
        put :update, {:id => t_json_entity.to_param, :t_json_entity => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested t_json_entity" do
      t_json_entity = TJsonEntity.create! valid_attributes
      expect {
        delete :destroy, {:id => t_json_entity.to_param}, valid_session
      }.to change(TJsonEntity, :count).by(-1)
    end

    it "redirects to the t_json_entities list" do
      t_json_entity = TJsonEntity.create! valid_attributes
      delete :destroy, {:id => t_json_entity.to_param}, valid_session
      response.should redirect_to(t_json_entities_url)
    end
  end

end
